#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] && exit 0

uci -q get cf_ip_speed_client.main.enabled >/dev/null || uci set cf_ip_speed_client.main.enabled='0'
uci -q get cf_ip_speed_client.main.ip_mode >/dev/null || uci set cf_ip_speed_client.main.ip_mode='dual'
uci -q get cf_ip_speed_client.main.include_443 >/dev/null || uci set cf_ip_speed_client.main.include_443='1'
uci -q get cf_ip_speed_client.main.custom_ports >/dev/null || uci set cf_ip_speed_client.main.custom_ports=''
uci -q get cf_ip_speed_client.main.test_url >/dev/null || uci set cf_ip_speed_client.main.test_url=''
uci -q get cf_ip_speed_client.main.schedule_mode >/dev/null || uci set cf_ip_speed_client.main.schedule_mode='daily'
uci -q get cf_ip_speed_client.main.interval_hours >/dev/null || uci set cf_ip_speed_client.main.interval_hours='6'
uci -q get cf_ip_speed_client.main.daily_hour >/dev/null || uci set cf_ip_speed_client.main.daily_hour='3'
uci -q get cf_ip_speed_client.main.daily_minute >/dev/null || uci set cf_ip_speed_client.main.daily_minute='0'
uci -q get cf_ip_speed_client.main.result_file >/dev/null || uci set cf_ip_speed_client.main.result_file='/tmp/cf-ip-speed-client/result.csv'
uci -q get cf_ip_speed_client.main.edgetunnel_sync_enabled >/dev/null || uci set cf_ip_speed_client.main.edgetunnel_sync_enabled='0'
uci -q get cf_ip_speed_client.main.edgetunnel_sync_url >/dev/null || uci set cf_ip_speed_client.main.edgetunnel_sync_url=''
uci -q get cf_ip_speed_client.main.edgetunnel_sync_password >/dev/null || uci set cf_ip_speed_client.main.edgetunnel_sync_password=''
uci -q get cf_ip_speed_client.main.edgetunnel_sync_v4_count >/dev/null || uci set cf_ip_speed_client.main.edgetunnel_sync_v4_count='20'
uci -q get cf_ip_speed_client.main.edgetunnel_sync_v6_count >/dev/null || uci set cf_ip_speed_client.main.edgetunnel_sync_v6_count='10'
uci -q get cf_ip_speed_client.main.log_clear_interval >/dev/null || uci set cf_ip_speed_client.main.log_clear_interval='weekly'
uci commit cf_ip_speed_client
exit 0
